# Generated by Django 4.1.3 on 2022-11-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newlogin", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profile/default.jpg", upload_to="profile/"
            ),
        ),
    ]
